//
//  Book+CoreDataProperties.swift
//  BookShelf//
//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//

import Foundation
import CoreData

extension Book{

	@nonobjc public class func fetchRequest() -> NSFetchRequest<Book> {
        return NSFetchRequest<Book>(entityName: "Book")
    }
    
	@NSManaged public var ISBN: String?
	@NSManaged public var title: String?
	@NSManaged public var description_: String?
	@NSManaged public var pageCount: Int32
	@NSManaged public var publisher: String?
	@NSManaged public var publishedDate: String?
	@NSManaged public var imgUrl: String?
    @NSManaged public var belongsTo: Shelf?
    
}
