//
//  Book+CoreDataClass.swift
//  BookShelf//
//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//

import Foundation
import CoreData

@objc(Book)
public class Book: NSManagedObject {
    
}
