//
//  FirebaseHandler.swift
//  BookShelf//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//

import FirebaseDatabase

class FirebaseHandler{
	
	func getReference(reference : String) -> DatabaseReference{
	
		return Database.database().reference(withPath: reference)
	}
	
	func getReference() -> DatabaseReference{
	
		return Database.database().reference()
	}
	
	func saveUser(user : User ) -> Void{
		
		// TODO REPLACE WITH YOUR FIREBASE CONSOLE REF
        let ref = getReference(reference: "users/" + user.access_email.replacingOccurrences(of: ".", with: "*"))
		
		ref.setValue(user.toAnyObject())
	}
	
	func observeUser() -> Void{
		
		// TODO REPLACE WITH YOUR FIREBASE CONSOLE REF
		let ref = getReference(reference: "users")
		
		ref.observe(.value, with: { snapshot in
				
			// TODO REPLACE WITH YOUR ACTION				
			var newItems: [User] = []
			  
			for item in snapshot.children {
				let  user = User(snapshot: item as! DataSnapshot)
				newItems.append(user)
			} 
			//self.items = newItems
		})
	}
    
    func getUser(access_email : String) -> DatabaseReference{
        
        return getReference(reference: "users/"+access_email.replacingOccurrences(of: ".", with: "*"))
    }
	
	func deleteUser(user : User) -> Void{
		
		getReference(reference: "users/"+user.access_email).removeValue()
	}
	            
}
