//
//  PreferenceHandler.swift
//  BookShelf//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//

import Foundation

class PreferenceHandler{
    
    var defaults : UserDefaults
    
    init(){
        defaults = UserDefaults.standard
    }
    
    func resetUser(){
        defaults.removeObject(forKey: "accessEmail")
        defaults.removeObject(forKey: "password");
        defaults.removeObject(forKey: "userName");
        defaults.removeObject(forKey: "userSurname");
        defaults.synchronize()
    }
    
    func storeCurrentShelfName(name: String){
        
        defaults.set(name, forKey: "currentShelfName");
    }
    
    func resetCurrentShelfName(){
        
        defaults.removeObject(forKey: "currentShelfName");
        defaults.synchronize()
    }
    
    func storeAccessEmail(value: String){
        
        defaults.set(value, forKey: "accessEmail");
    }
    
    func getAccessEmail() -> String?{
        
        if defaults.object(forKey: "accessEmail") != nil
        {
            return defaults.string(forKey: "accessEmail");
        }else{
            
            return nil
        }
    }
    
    func storePassword(value: String){
        
        defaults.set(value, forKey: "password");
    }
    
    func getPassword() -> String?{
        
        if defaults.object(forKey: "password") != nil
        {
            return defaults.string(forKey: "password");
        }else{
            
            return nil
        }
    }
    
    func storeUserName(value: String){
        
        defaults.set(value, forKey: "userName");
    }
    
    func getUserName() -> String?{
        
        if defaults.object(forKey: "userName") != nil
            {
                return defaults.string(forKey: "userName");
        }else{
            return nil
        }
    }
    
    func storeUserSurname(value: String){
        
        defaults.set(value, forKey: "userSurname");
    }
    
    func getUserSurname() -> String?{
        
        if defaults.object(forKey: "userSurname") != nil
        {
            return defaults.string(forKey: "userSurname");
        }else{
            return nil
        }
    }
    
    func storeBookCount(value: Int){
        
        defaults.set(value, forKey: "bookCount");
    }
    
    func getBookCount() -> Int{
        
        if defaults.object(forKey: "bookCount") != nil
        {
            return defaults.integer(forKey: "bookCount");
        }else{
            return 0
        }
    }
    
    func storeUser(user: User){
        
        defaults.set(user.user_name, forKey: "userName");
        defaults.set(user.user_surname, forKey: "userSurname");
        defaults.set(user.access_email, forKey: "accessEmail");
        defaults.set(user.password, forKey: "password");
    }
    
    func getPrefDict() -> Dictionary<String, Any>{
        
        return UserDefaults.standard.dictionaryRepresentation()
    }
}
