//
//  StorageHandler.swift
//  BookShelf//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//

import Foundation

class StorageHandler{
	
	let FileName = "about.txt";

	func readFile(file : String) -> String{
		
		if let dir = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first {
	    	let path = dir.appendingPathComponent(file)
	    	
			var text = "";
		    do {
		         text = try String(contentsOf: path, encoding: String.Encoding.utf8)
		    }
		    catch {/* error handling here */}  
		    
		    return text;
		}else{ return ""; }  
	}  
	
	func writeFile(file : String, content : String) -> Bool{
		
		if let dir = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first {
	    	
	    	let path = dir.appendingPathComponent(file)
		    do {
		        try content.write(to: path, atomically: false, encoding: String.Encoding.utf8)
		    }
		    catch {
		    	return false
		    }
		    return true;
		    
		}else{ return false; }  
	}             
}
