//
//  BookDetailViewController.swift"
//  BookDetail//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//
import UIKit

class BookDetailViewController: UIViewController
 {
    @IBOutlet weak var isbnTextL: UILabel!
    @IBOutlet weak var titleTextL: UILabel!
    @IBOutlet weak var descTextL: UILabel!
    @IBOutlet weak var pubTextL: UILabel!
    @IBOutlet weak var pubDateTextL: UILabel!
    @IBOutlet weak var pageCountTextL: UILabel!
    @IBOutlet weak var inShelfTextL: UILabel!
    
    var book: Book? = nil
    var shelfName: String = ""
    var isbnText: String = ""
    var titleText: String = ""
    var descText: String = ""
    var pubText: String = ""
    var pubDateText: String = ""
    var pageCountText: String = ""
    var inShelfText: String = ""
    
	override func viewDidLoad() {
	    super.viewDidLoad()
        
        isbnTextL.text = ""
        titleTextL.text = ""
	}
}
