//
//  LoginViewController.swift"
//  Login//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//
import UIKit
import FirebaseDatabase

class LoginViewController: UIViewController
 {
    @IBOutlet weak var accessEmailText: UITextField!
    @IBOutlet weak var passwordText: UITextField!
    @IBOutlet weak var loginButton: UIButton!
    @IBOutlet weak var registerLink: UIButton!
    
	override func viewDidLoad() {
	    super.viewDidLoad()
        
        accessEmailText.placeholder = "email"
        passwordText.placeholder = "password"
        loginButton.layer.cornerRadius = 2
        
        let prefHandler = PreferenceHandler()
        let email = prefHandler.getAccessEmail()
        let password = prefHandler.getPassword()
        
        if( email != nil && password != nil){
        
            self.CheckInfo(email : (email)!, password: (password)!)
        }else{
        
            let fileStorage = StorageHandler()
            let aboutContent = "BookShelf is an application that lets you storing and organizing your books in an immediate way, " +
                "thanks to its ISBN scanner.\n" +
                "\n" +
                "Developed by Alessio Rossotti\n" +
                "\n" +
            "Copyright © 2017. All rights reserved."
            
            _ = fileStorage.writeFile(file: "about.txt", content: aboutContent)
        }
	}
	
    func CheckInfo(email : String, password: String){
        
        if (email == "" || password == ""){
            self.displayError()
            return
        }
        let firebaseHandler = FirebaseHandler()
        let userRef = firebaseHandler.getUser(access_email: email)
        
        userRef.observe(.value, with: { snapshot in
            
            let user = User(snapshot: snapshot)
            
            if( user.password == password){
                self.Login(user: user)
                
            }else{
                self.displayError()
                return
            }
        })
    }
    
    func displayError(){
    
        let alert = UIAlertController(title: "Wrong Info", message: "user and/or password incorrect", preferredStyle: UIAlertControllerStyle.alert)
        alert.addAction(UIAlertAction(title: "Ok", style: UIAlertActionStyle.default, handler: nil))
        self.present(alert, animated: true, completion: nil)

    }
    
    @IBAction func loginButtonClick(_ sender: Any) {
        CheckInfo(email: self.accessEmailText.text! , password : self.passwordText.text!)
        
    }
    
    @IBAction func goToRegister(_ sender: Any) {
    
        //Go to the RegisterViewController
        let vc = self.storyboard?.instantiateViewController(withIdentifier: "Register")
        self.present(vc!, animated: true, completion: nil)
    }
    
    func Login(user: User){
        let prefHandler = PreferenceHandler()
        prefHandler.storeUser(user: user)
        
        //Go to the HomeViewController if the login is sucessful
        self.performSegue(withIdentifier: "TabBar", sender: nil)
    }
    
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
	}
}
