//
//  RegisterViewController.swift"
//  Register//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//
import UIKit

class RegisterViewController: UIViewController
 {
    
    @IBOutlet weak var registButton: UIButton!
    @IBOutlet weak var loginLink: UIButton!
    
    @IBOutlet weak var nameText: UITextField!
    @IBOutlet weak var surnameText: UITextField!
    @IBOutlet weak var emailText: UITextField!
    @IBOutlet weak var passwordText: UITextField!
	
	override func viewDidLoad() {
	    super.viewDidLoad()
		registButton.layer.cornerRadius = 2
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}

    @IBAction func loginLinkClick(_ sender: Any) {
        //Go to the LoginViewController
        let vc = self.storyboard?.instantiateViewController(withIdentifier: "Login")
        self.present(vc!, animated: true, completion: nil)
    }
    
    @IBAction func registerButtonClick(_ sender: Any) {
        
        let email = emailText.text;
        let password = passwordText.text
        let name = nameText.text
        let surname = surnameText.text
        
        if( email != "" && password != "" && name != "" && surname != ""){
        
            let user = User(access_email: email!, password: password!, user_name: name!, user_surname: surname!)
            let firebaseDB = FirebaseHandler()
            firebaseDB.saveUser(user: user)
            
            displaySuccess()
        }
    }
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
	}
    
    func displaySuccess(){
        
        let alert = UIAlertController(title: "Succesfully registered", message: "Go to login page and provide info", preferredStyle: UIAlertControllerStyle.alert)
        alert.addAction(UIAlertAction(title: "Ok", style: UIAlertActionStyle.default, handler: nil))
        self.present(alert, animated: true, completion: nil)
        
    }
}
