//
//  SettingsViewController.swift"
//  Settings//
//  Automatically generated by MobileCodeGenerator 3.
//  Copyright © 2017 . All rights reserved.
//
import UIKit

class SettingsViewController: UIViewController
 {
    @IBOutlet weak var editName: UITextField!
    @IBOutlet weak var editSurname: UITextField!
    @IBOutlet weak var editPassword: UITextField!
    @IBOutlet weak var editEmail: UITextField!
    
    @IBOutlet weak var updateButton: UIButton!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
	override func viewDidLoad() {
        
	    super.viewDidLoad()
        let prefHandler = PreferenceHandler()
        
        editName.text = prefHandler.getUserName()
        editSurname.text = prefHandler.getUserSurname()
        editEmail.text = prefHandler.getAccessEmail()
        editPassword.text = prefHandler.getPassword()
    }
	
    @IBAction func updateInfo(_ sender: Any) {
        
        let user = User(access_email: editEmail.text!, password: editPassword.text!, user_name: editName.text!, user_surname: editSurname.text! )
        
        let fireHandler = FirebaseHandler()
        fireHandler.saveUser(user: user)
        
    }

    
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
	}
}
